# Generated by Django 4.2.17 on 2025-08-09 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('landmarket', '0003_savedsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('inquiry_new', 'New Inquiry'), ('inquiry_response', 'Inquiry Response'), ('listing_approved', 'Listing Approved'), ('listing_rejected', 'Listing Rejected'), ('listing_pending', 'Listing Pending Approval'), ('property_favorited', 'Property Favorited'), ('system_welcome', 'Welcome Message'), ('system_update', 'System Update'), ('admin_message', 'Admin Message')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, default='{}')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='landmarket__recipie_abc32e_idx'), models.Index(fields=['recipient', 'created_at'], name='landmarket__recipie_45f421_idx'), models.Index(fields=['notification_type'], name='landmarket__notific_cf3426_idx')],
            },
        ),
    ]
